version: '3'
services:
  ai_ticket:
    image: ai_ticket
    build:
      context: .
    restart: unless-stopped
    # Optional: Add environment variables for KOBOLDCPP_API_URL if needed here
    # environment:
    #   - KOBOLDCPP_API_URL=http://host.docker.internal:5001/api
    # (Note: host.docker.internal is for Docker Desktop to access host services)
    # Or it might be expected that KOBOLDCPP_API_URL is set in the environment
    # where 'docker-compose up' is run, or in an .env file.
