version: '3'
services:
  ai_ticket:
    image: ai_ticket
    build:
      context: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    # Optional: Add environment variables for KOBOLDCPP_API_URL if needed here
    # environment:
    #   - KOBOLDCPP_API_URL=http://host.docker.internal:5001/api
    # (Note: host.docker.internal is for Docker Desktop to access host services)
    # Or it might be expected that KOBOLDCPP_API_URL is set in the environment
    # where 'docker-compose up' is run, or in an .env file.
