version: '3'
services:
  ai_ticket:
    image: jmikedupont2/ai-ticket:latest # Or your specific image tag
    # This service now directly uses the pre-built image.
    # Ensure KOBOLDCPP_API_URL is available in the environment this compose file is run in,
    # or add it here if it's static and you want to embed it.
    # environment:
    #   - KOBOLDCPP_API_URL=http://host.docker.internal:5001/api
    # network_mode: "host" # If KoboldCPP is on host and not otherwise accessible
    extra_hosts: # Useful if KoboldCPP is running on the host machine
      - "host.docker.internal:host-gateway"
    # Add any other necessary configurations for ai_ticket, like ports if it exposes one.
    # ports:
    #   - "8000:8000" # Example if ai_ticket service ran on port 8000
    restart: unless-stopped
