name: Run Application
on:
  workflow_dispatch :   #only run when requested
jobs:
  run_application:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'true'        
    - name: Run application with docker-compose
      run: docker-compose up --no-build
